### ISSUE TITLE
could not able to clone in local device

### ISSUE THREAD

**Issue by Rohit3085** [grimmlab/UAVWeedSegmentation#1]
When cloning, permission denied message is popping up. please see the screenshot for more info.

![Screenshot 2023-04-13 153412](https://user-images.githubusercontent.com/89350242/231726283-88a77632-8b30-4ce8-b7fd-6b46657db333.png)

**Comment by ngenze** [comment]
Hi, 

I could not reproduce the issue and am able to clone the repository. Do you have a SSH key associated with your GitHub account, as you are trying to use SSH for cloning? Please refer to the following link for more information about authorization:
https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey
