### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by MerlockMoe** [grimmlab/UAVWeedSegmentation#2]
Servus, ich studiere an der HS Kempten Robotik und bin Werkstudent bei ITQ am Business Campus in München. Für den Makeathon auf Gran Canaria im Februar/März darf ich die Challenge stellen und hätte gerne verschiedene Datensätze zur Verfügung. Könnten Sie mir den Datensatz rein für Lehrzwecke und für diesen Zeitraum zur Verfügung stellen?
FG, Johannes Kruckow

**Comment by dominikgrimm** [comment]
Lieber Herr Kruckow,
wie im Readme angegeben sind die Daten unter https://data.mendeley.com/datasets/4hh45vkp38/5 zum Download zu finden.
Viele Grüße,
Dominik

**Comment by MerlockMoe** [comment]
Danke für die schnelle Rückmeldung. Diese Daten habe ich gesehen. Aber das können doch niemals die Trainingsdaten sein, oder doch? Das wäre dann ja bahnbrechend. Ich meine in einem Vortrag über das Model etwas über mehr als 10.000 Trainingsbilder gehört zu haben?

**Comment by dominikgrimm** [comment]
Das Paper enthält alle Details zu den Daten und der Aufteilung der Bilder in einzelne Patches. Nur diese Daten wurden für dieses Paper verwendet. Unsere Vorträge beziehen sich auf mehrere Teilprojekte eines größeren Projektes, für das wir mehrere tausend Bilder gesammelt und annotiert haben. Diese Daten wurden in verschiedenen Publikationen verarbeitet. Für weitere Informationen stehen wir gerne zur Verfügung. Dazu bitte eine E-Mail an mich schicken.
